server:
  port: 8088
  servlet:
    context-path: /bootcamp
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://fqgvidxdqyklfl:d52c9d280fc2f4f9529d40333ae9fb097497efc78b36052681262193883c52b0@ec2-54-90-211-192.compute-1.amazonaws.com:5432/d3b2s9lgbt8n6b
    username: fqgvidxdqyklfl
    password: d52c9d280fc2f4f9529d40333ae9fb097497efc78b36052681262193883c52b0
  jpa:
    showsql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / backend
